# -*- coding: utf-8 -*-
"""week 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DBlwHY28snNq1lj5xtpq4danMXXSupf3
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/annual-enterprise-survey-2023-financial-year-provisional (1).csv')
df

df.head()

df.tail()

df.describe()

df.size

df.shape

df.info()

